[config]
default_to_workspace = false

[env]
TOOLCHAIN_V = "nightly-2022-01-20"


[tasks.env]
script_runner = "@shell"
script = ['''
    rustup override set ${TOOLCHAIN_V}
''']

[tasks.start]
clear = true
command = "cargo"
args = ["watch", "-cx", "run"]


[tasks.watch]
clear = true
command = "cargo"
args = ["watch", "-cx", "clippy"]

[tasks.check]
clear = true
script_runner = "@shell"
script = ['''
    cargo clippy --all-targets --all-features -- -D warnings
    cargo fmt -- --check
''']

[tasks.test]
clear = true
script_runner = "@shell"
script = ['''
    cargo test -- --test-threads=1
''']
