unstable_features = true # for v1
control_brace_style = "ClosingNextLine"
error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Module"
newline_style = "Native"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true

max_width = 100
fn_call_width = 90
chain_width = 80
array_width = 80
single_line_if_else_max_width = 50
